export const dict = {
  /*telegram msg*/
  msg_info: 'ИНФО',
  msg_name: 'Имя',
  msg_phone: 'Телефон',
  msg_email: 'Почта',
  msg_street: 'Улица',
  msg_city: 'Город',
  msg_order_id: 'Номер заказа',
  msg_total_price: 'Сумма',
  msg_order: 'ЗАКАЗ',
  msg_item_title: 'Порода',
  msg_item_id: 'Номер питомца',
  msg_item_price: 'Цена',
  msg_notes: 'Заметки',
  /* header */
  search: 'Search',
  delivery: 'Delivery',
  contacts: 'Contacts',
  about: 'About project',
  reviews: 'Reviews',
  /* goods */
  years: (n) => n === 1 ? 'year' : 'years',
  months: (n) => n === 1 ? 'month' : 'months',
  weeks: (n) => n === 1 ? 'week' : 'weeks',
  days: (n) => n === 1 ? 'day' : 'days',
  male: 'Boy',
  female: 'Girl',
  /*product details*/
  age: 'Age',
  /*sorting*/
  sort_by: 'Sort by',
  'price-high': 'Price: High to Low',
  'price-low': 'Price: Low to High',
  'age-high': 'Age: High to Low',
  'age-low': 'High: Low to High',
  /*detailed info*/
  identifier: 'Identifier',
  open_big_picture: 'Open full size picture',
  delivery_info: 'Delivery is free. We will personally deliver a pet to your apartment in the shortest possible time',
  payment_info: 'At the moment you can pay only to the courier',
  order_success: 'Successfully. Your order number is: ',
  /*no order*/
  all_category: 'All pets',
  dog_category: 'Dogs',
  cat_category: 'Cats',
  fish_category: 'Fish',
  bird_category: 'Birds',
  black: 'Black',
  white: 'White',
  gray: 'Gray',
  red: 'Red',
  brown: 'Brown',
  orange: 'Orange',
  yellow: 'Yellow',
  green: 'Green',
  blue: 'Blue',
  apply: 'Apply',
  remove_filters: 'Remove filters',
  price: 'Price',
  is_sterile: 'Is pet sterilized',
  cart_is_empty: 'Cart is empty',
  continue_shopping: 'Continue shopping',
  street_example: 'Broadway St. 3',
  city_example: 'New York',
  search_result: 'Search',
};